### PR TITLE
Added support for HTML formatting in label

### PR DESCRIPTION
**Pull request by mstahv**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java, line 127 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50#-LDf_G4NA5wWq-EA7tJQ:-LDf_G4NA5wWq-EA7tJR:b-ago326) ([raw file](https://github.com/vaadin/vaadin-checkbox-flow/blob/00f9a14ace8eca75b08ab1381c8d763c88777f56/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java#L127)):*
> ```Java
>      * formatting.
>      *
>      * <p>Note, the given html content is not sanitized by the framework.</p>
> ```

This could a bit more forcefully inform that the developer is responsible for the html content.
`As the given caption is rendered in the browser as HTML and not sanitized by the framework. It is up to the developer to ensure that no harmful HTML is used for the caption.`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50)*

**Comment by mstahv** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java, line 127 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50#-LDf_G4NA5wWq-EA7tJQ:-LDfk_nt96UsEdffgue1:b-w0cwab) ([raw file](https://github.com/vaadin/vaadin-checkbox-flow/blob/00f9a14ace8eca75b08ab1381c8d763c88777f56/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java#L127)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This could a bit more forcefully inform that the developer is responsible for the html content.
`As the given caption is rendered in the browser as HTML and not sanitized by the framework. It is up to the developer to ensure that no harmful HTML is used for the caption.`
</blockquote></details>

Is that a request to change this or just a comment? I have no idea how this Reviewable works so I don't know what to do. The text in your comment is not clear english and don't provide valuable information for end user. I'd leave this as is or change it to some prompt well though XSS warning text used somewhere else too. Is there such?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java, line 127 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50#-LDf_G4NA5wWq-EA7tJQ:-LDfrLet-SjMNYA1sZY7:b-o5c4u5) ([raw file](https://github.com/vaadin/vaadin-checkbox-flow/blob/00f9a14ace8eca75b08ab1381c8d763c88777f56/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java#L127)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Is that a request to change this or just a comment? I have no idea how this Reviewable works so I don't know what to do. The text in your comment is not clear english and don't provide valuable information for end user. I'd leave this as is or change it to some prompt well though XSS warning text used somewhere else too. Is there such?
</blockquote></details>

The note should note that it's up to the developer to check that no hagmful html is set throgh this. See fw setHtmlCaption. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50)*

**Comment by mstahv** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java, line 127 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50#-LDf_G4NA5wWq-EA7tJQ:-LDfu_CaAhYU1xPmD6Xh:b-8ej241) ([raw file](https://github.com/vaadin/vaadin-checkbox-flow/blob/00f9a14ace8eca75b08ab1381c8d763c88777f56/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java#L127)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The note should note that it's up to the developer to check that no hagmful html is set throgh this. See fw setHtmlCaption. 
</blockquote></details>

Derived a new version from a javadoc used in FW8.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50)*

**Comment by mstahv** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java, line 127 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50#-LDf_G4NA5wWq-EA7tJQ:-LDfukNC8GuykSpwqvCO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox-flow/blob/00f9a14ace8eca75b08ab1381c8d763c88777f56/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java#L127)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Derived a new version from a javadoc used in FW8.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox-flow/50)*

**Pull request merged**
